### ISSUE TITLE
Use Extracted Krab Repository

### ISSUE THREAD

**Issue by postables** [RTradeLtd/kaas#9]
# Assignee: [arku](https://github.com/arku)

Currently `kaas` leverages an old version of `rtfs` which bundled `krab` inside. Since then `krab` has been extracted into a separate repository located [here](https://github.com/RTradeLtd/krab)

Work required for this ticket:
* Update dependencies, and change imports to use extracted krab repository instead of the krab repository bundled within `rtfs`

**Comment by arku** [comment]
@postables I am on it.

**Comment by arku** [comment]
> Update dependencies, and change imports to use extracted krab repository instead of the krab repository bundled within rtfs

@postables Looks like `kaas` uses the `krab` package bundled within `grpc`. I can go ahead and replace it with `github.com/RTradeLtd/krab` right?

**Comment by postables** [comment]
Reposting my message from our DM's in-case it is helpful to other people in the future:

```
so the way gRPC works is you use protocol buffers as an IDL (Interface Definition Language) and both as a message interchange format
you write these buffers in .proto files, and then you can compile server+clients in multiple different languages
github.com/RTradeLtd/grpc is a central repository where we store our protocol buffers, and various gRPC helpers for multiple different projects
so krab in grpc really just defines the protocol buffers
````
